### PR TITLE
 Added support for options 

### PR DESCRIPTION
**Pull request by stevenpkg**
changed assistant constructor to just date (no if else)

Testing demo at http://watson-assistant-simple-options.mybluemix.net/

### CODE REVIEW

**Comment by stevenpkg** [comment]
@Oliver-I please watch this as I am on holiday from Friday

**Comment by stevenpkg** [comment]
Type 'turn on' to test options

**Comment by Oliver-I** [comment]
@stevenpkg Are there any changes required for this so that German can merge?

**Comment by stevenpkg** [comment]
@germanattanasio  have fix formatting errors, had to remove one unit test as it was failing after the last merge from origin, have slacked you the error.

Can you please merge, and I can fix the unit test when I return from holiday, or if you get time to fix.

**Comment by germanattanasio** [comment]
I'll work on this @stevenpkg

**Comment by mitchmason** [comment]
Rather than just having the buttons show up as bullet points, can we make them clickable options as outlined here:
https://console.bluemix.net/docs/services/conversation/implement-responses.html#implementing-responses.
We should also support images, preferably pause as well to make this a sample of all new features

**Comment by Oliver-I** [comment]
@mitchmason I'll talk to Steve about changing this.

**Comment by Oliver-I** [comment]
@stevenpkg Please see the above.

**Pull request merged**
